import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Demo React Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Demo React Next.js</h1>
        <Link href="/products">
          <a>Products</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
